### ISSUE TITLE
Additional "Go to File" items settings array

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#11683]
There are files in my `node_modules` folder that I would like to open using the <kbd>ctrl+p</kbd> shortcut, as these files (In my case) have css variables that I don't have memorized and I would like an easy way to open them without having to navigate through the explorer sidebar to the file.

```css
/* Just an example file */
:root {
  --one: 1px;
  --two: 2px;
}
```

```json
{
  "files.extra.include": [
    "node_modules/-org/package/style/themes/my-theme.css"
  ]
}
```
