### ISSUE TITLE
Action button font size is unusually large on modal dialogs

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#20056]
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/30305945/226956475-639ea4bb-429c-4671-b9ac-6f9e589f2521.png">

Inspecting the CSS shows 
```css
-monaco-dialog-message-body>.link>p, .monaco-dialog-box>.dialog-buttons-row>.dialog-buttons>.monaco-button {
    font-size: 16px;
}
```
