### ISSUE TITLE
CSS/SCSS format.spaceAroundSelectorSeparator not working correctly

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#35280]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.84.2 (Universal)
- OS Version: Mac 13.5.2 (22G91)

Steps to Reproduce:

1. Use an operator in an -if statement
2. Format the code
3. Notice the right side of the operator space is removed

Ex. 
```scss
-for $i from 1 through $positions {
  &.pos-{$i} {
    left: $i * if($i !=$positions, 10%, 15%);
  }
}

-if $positions ==10 {
  &.pos11 {
    left: 100%;
  }
}
```
