### ISSUE TITLE
Allow to set text width for markdown output in notebooks

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#51068]
My screen is ~60cm width, output of this width is very difficult to read:

<img width="1734" alt="image" src="https://github-com/user-attachments/assets/3fa46f05-4941-4abb-93d4-e673e67db062">

I'm using this CSS rule with `display(HTML(...))` as a workaround:

```css
.markup .preview {width: 100ch !important; }
```

but it's just that, a workaround.
